services:
  - type: web
    plan: free
    runtime: image
    name: n8n-service
    image:
      url: docker.io/n8nio/n8n:latest

    envVars:
      - key: N8N_ENCRYPTION_KEY
        generateValue: true

      - key: DB_TYPE
        value: postgresdb

      - key: DB_POSTGRESDB_DATABASE
        value: postgres

      - key: DB_POSTGRESDB_HOST
        value: db.akqjvytmeqfhuirfzppq.supabase.co

      - key: DB_POSTGRESDB_PORT
        value: "5432"

      - key: DB_POSTGRESDB_USER
        value: postgres

      - key: DB_POSTGRESDB_PASSWORD
        value: Q4rLq2cUf#S5gu#

      # SSL é obrigatório para Supabase
      - key: DB_POSTGRESDB_SSL
        value: "true"
