services:
  - type: web
    plan: free
    runtime: image
    name: n8n-service
    image:
      url: docker.io/n8nio/n8n:latest

    envVars:
      - key: N8N_ENCRYPTION_KEY
        generateValue: true

      - key: N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS
        value: "true"

      # Use Supavisor Session Pooler (IPv4 compatível)
      - key: DB_TYPE
        value: postgresdb
      - key: DB_POSTGRESDB_CONNECTION_STRING
        value: postgresql://postgres.akqjvytmeqfhuirfzppq:$[DB_PASSWORD]@aws-1-sa-east-1.pooler.supabase.com:5432/postgres
