services:
  - type: web
    plan: free
    runtime: image
    name: n8n-service
    image:
      url: docker.io/n8nio/n8n:latest

    envVars:
      # Chave de criptografia do n8n (não altere depois de gerar)
      - key: N8N_ENCRYPTION_KEY
        generateValue: true

      # Configuração do banco (Supabase)
      - key: DB_TYPE
        value: postgresdb
      - key: DB_POSTGRESDB_DATABASE
        value: postgres
      - key: DB_POSTGRESDB_HOST
        value: db.akqjvytmeqfhuirfzppq.supabase.co
      - key: DB_POSTGRESDB_PASSWORD
        sync: false   # Valor será configurado manualmente no painel do Render
      - key: DB_POSTGRESDB_USER
        value: postgres
      - key: DB_POSTGRESDB_PORT
        value: "5432"
