services:
  - type: web
    plan: free
    runtime: image
    name: n8n-service
    image:
      url: docker.io/n8nio/n8n:latest

    envVars:
      - key: N8N_ENCRYPTION_KEY
        generateValue: true

      - key: DB_TYPE
        value: postgresdb

      - key: DB_POSTGRESDB_CONNECTION_STRING
        value: postgresql://postgres.akqjvytmeqfhuirfzppq:Q4rLq2cUf#S5gu#@aws-1-sa-east-1.pooler.supabase.com:5432/postgres?sslmode=require

